-- HunarHub Database Schema
-- Version: 1.0.0
-- Generated by Antigravity

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-------------------------------------------------------------------------------
-- 1. Profiles Table (Extends auth.users)
-------------------------------------------------------------------------------
CREATE TYPE user_role AS ENUM ('student', 'recruiter', 'admin');

CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role user_role DEFAULT 'student',
  full_name TEXT,
  avatar_url TEXT,
  headline TEXT,
  bio TEXT,
  skills TEXT[] DEFAULT '{}',
  education JSONB DEFAULT '[]', -- structured as [{school, degree, year}]
  company_details JSONB DEFAULT '{}', -- for recruiters: {name, website, size}
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Secure the profiles table
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone." 
  ON profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." 
  ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." 
  ON profiles FOR UPDATE USING (auth.uid() = id);

-------------------------------------------------------------------------------
-- 2. Projects Table
-------------------------------------------------------------------------------
CREATE TABLE projects (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  cover_image_url TEXT,
  tags TEXT[] DEFAULT '{}',
  demo_link TEXT,
  github_link TEXT,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Projects are viewable by everyone." 
  ON projects FOR SELECT USING (true);

CREATE POLICY "Users can insert their own projects." 
  ON projects FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own projects." 
  ON projects FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own projects." 
  ON projects FOR DELETE USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 3. Internships Table
-------------------------------------------------------------------------------
CREATE TYPE internship_type AS ENUM ('Full-time', 'Part-time', 'Remote');
CREATE TYPE internship_status AS ENUM ('Open', 'Closed');

CREATE TABLE internships (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  recruiter_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  company_name TEXT NOT NULL,
  location TEXT,
  type internship_type DEFAULT 'Full-time',
  salary_range TEXT,
  requirements TEXT[] DEFAULT '{}',
  status internship_status DEFAULT 'Open',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE internships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Internships are viewable by everyone." 
  ON internships FOR SELECT USING (true);

CREATE POLICY "Recruiters can insert internships." 
  ON internships FOR INSERT 
  WITH CHECK (auth.uid() = recruiter_id); -- Ideally check profile role too via trigger/function

CREATE POLICY "Recruiters can update their own internships." 
  ON internships FOR UPDATE USING (auth.uid() = recruiter_id);

-------------------------------------------------------------------------------
-- 4. Applications Table
-------------------------------------------------------------------------------
CREATE TYPE application_status AS ENUM ('pending', 'interviewing', 'accepted', 'rejected');

CREATE TABLE applications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  internship_id UUID REFERENCES internships(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  cover_letter TEXT,
  resume_url TEXT,
  status application_status DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(internship_id, student_id)
);

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

-- Students can see their own applications
CREATE POLICY "Students can view own applications" 
  ON applications FOR SELECT 
  USING (auth.uid() = student_id);

-- Recruiters can see applications for their internships
CREATE POLICY "Recruiters can view applications for their internships" 
  ON applications FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM internships 
      WHERE internships.id = applications.internship_id 
      AND internships.recruiter_id = auth.uid()
    )
  );

INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read access to resumes"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'resumes');

CREATE POLICY "Authenticated users can upload resumes"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  );

CREATE POLICY "Owners can update their resumes"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  )
  WITH CHECK (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  );

CREATE POLICY "Owners can delete their resumes"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  );

-- Students can create applications
CREATE POLICY "Students can apply" 
  ON applications FOR INSERT 
  WITH CHECK (auth.uid() = student_id);

-- Recruiters can update status
CREATE POLICY "Recruiters can update application status" 
  ON applications FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM internships 
      WHERE internships.id = applications.internship_id 
      AND internships.recruiter_id = auth.uid()
    )
  );

-------------------------------------------------------------------------------
-- 5. Messages Table
-------------------------------------------------------------------------------
CREATE TABLE messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  attachment_url TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own messages" 
  ON messages FOR SELECT 
  USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Users can send messages" 
  ON messages FOR INSERT 
  WITH CHECK (auth.uid() = sender_id);

-------------------------------------------------------------------------------
-- 6. Notifications Table
-------------------------------------------------------------------------------
CREATE TYPE notification_type AS ENUM ('application_update', 'new_message', 'project_like', 'follow');

CREATE TABLE notifications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  type notification_type NOT NULL,
  reference_id UUID, -- Generic reference to project/app/message ID
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications" 
  ON notifications FOR SELECT 
  USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 7. Triggers for Automatic Profile Creation
-------------------------------------------------------------------------------
-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    COALESCE((new.raw_user_meta_data->>'role')::user_role, 'student')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-------------------------------------------------------------------------------
-- 8. Students Table (detail profile for student users)
-------------------------------------------------------------------------------

CREATE TABLE students (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  email TEXT,
  college TEXT,
  education TEXT,
  skills TEXT[] DEFAULT '{}',
  experience TEXT,
  resume_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Students can view own record"
  ON students FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Students can insert own record"
  ON students FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Students can update own record"
  ON students FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-------------------------------------------------------------------------------
-- 9. Companies Table (detail profile for company users)
-------------------------------------------------------------------------------

CREATE TABLE companies (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  company_name TEXT NOT NULL,
  official_email TEXT,
  website TEXT,
  linkedin TEXT,
  industry TEXT,
  location TEXT,
  company_size TEXT,
  description TEXT,
  verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE companies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Companies can view own record"
  ON companies FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Companies can insert own record"
  ON companies FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Companies can update own record"
  ON companies FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Admins can view all companies
CREATE POLICY "Admins can view all companies"
  ON companies FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'admin'
    )
  );

-- Admins can update verified flag
CREATE POLICY "Admins can verify companies"
  ON companies FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role = 'admin'
    )
  );

-------------------------------------------------------------------------------
-- 10. Jobs Table
-------------------------------------------------------------------------------

CREATE TYPE job_type AS ENUM ('internship', 'fulltime');

CREATE TABLE jobs (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  type job_type NOT NULL,
  category TEXT,
  skills_required TEXT[] DEFAULT '{}',
  location TEXT,
  remote_type TEXT,
  duration TEXT,
  salary TEXT,
  paid BOOLEAN,
  openings INTEGER,
  deadline DATE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;

-- Everyone can view jobs
CREATE POLICY "Jobs are viewable by everyone"
  ON jobs FOR SELECT
  USING (true);

-- Only verified companies can post jobs
CREATE POLICY "Verified companies can create jobs"
  ON jobs FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM companies c
      WHERE c.id = company_id
        AND c.id = auth.uid()
        AND c.verified = TRUE
    )
  );

-- Companies can update their own jobs
CREATE POLICY "Companies can update own jobs"
  ON jobs FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM companies c
      WHERE c.id = jobs.company_id
        AND c.id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM companies c
      WHERE c.id = jobs.company_id
        AND c.id = auth.uid()
    )
  );

-------------------------------------------------------------------------------
-- 11. Job Applications Table
-------------------------------------------------------------------------------

CREATE TYPE job_application_status AS ENUM ('applied', 'shortlisted', 'rejected', 'selected');

CREATE TABLE job_applications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  job_id UUID NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  resume_url TEXT,
  cover_letter TEXT,
  status job_application_status DEFAULT 'applied',
  applied_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;

-- Students can see their own applications
CREATE POLICY "Students can view own job applications"
  ON job_applications FOR SELECT
  USING (auth.uid() = student_id);

-- Companies can see applications for their jobs
CREATE POLICY "Companies can view applications for their jobs"
  ON job_applications FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM jobs j
      JOIN companies c ON c.id = j.company_id
      WHERE j.id = job_applications.job_id
        AND c.id = auth.uid()
    )
  );

-- Students can apply to jobs
CREATE POLICY "Students can apply to jobs"
  ON job_applications FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = student_id);

-- Companies can update application status
CREATE POLICY "Companies can update job application status"
  ON job_applications FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1
      FROM jobs j
      JOIN companies c ON c.id = j.company_id
      WHERE j.id = job_applications.job_id
        AND c.id = auth.uid()
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1
      FROM jobs j
      JOIN companies c ON c.id = j.company_id
      WHERE j.id = job_applications.job_id
        AND c.id = auth.uid()
    )
  );

INSERT INTO storage.buckets (id, name, public)
VALUES ('resumes', 'resumes', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public read access to resumes"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'resumes');

CREATE POLICY "Authenticated users can upload resumes"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  );

CREATE POLICY "Owners can update their resumes"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  )
  WITH CHECK (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  );

CREATE POLICY "Owners can delete their resumes"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'resumes'
    AND auth.uid()::text = split_part(name, '/', 1)
  );

CREATE TABLE plans (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  monthly_price_inr INTEGER,
  currency TEXT DEFAULT 'INR',
  max_jobs_per_month INTEGER,
  featured_listings BOOLEAN DEFAULT FALSE,
  priority_ranking BOOLEAN DEFAULT FALSE,
  ai_resume_score BOOLEAN DEFAULT FALSE,
  skill_tests BOOLEAN DEFAULT FALSE,
  chat_enabled BOOLEAN DEFAULT FALSE,
  interview_scheduling BOOLEAN DEFAULT FALSE,
  certificate_generation BOOLEAN DEFAULT FALSE,
  company_rating_enabled BOOLEAN DEFAULT FALSE,
  stripe_price_id TEXT,
  razorpay_plan_id TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE company_subscriptions (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  plan_id UUID NOT NULL REFERENCES plans(id),
  status TEXT NOT NULL DEFAULT 'active',
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ,
  cancel_at_period_end BOOLEAN DEFAULT FALSE,
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  razorpay_customer_id TEXT,
  razorpay_subscription_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE company_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Plans are readable by everyone"
  ON plans FOR SELECT
  USING (true);

CREATE POLICY "Company can view own subscription"
  ON company_subscriptions FOR SELECT
  TO authenticated
  USING (company_id = auth.uid());

INSERT INTO plans (slug, name, description, monthly_price_inr, max_jobs_per_month, featured_listings, priority_ranking)
VALUES
  ('free', 'Free', 'Free plan with limited job posts', 0, 1, FALSE, FALSE),
  ('premium', 'Premium', 'Unlimited job posts with priority features', 49900, NULL, TRUE, TRUE)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    monthly_price_inr = EXCLUDED.monthly_price_inr,
    max_jobs_per_month = EXCLUDED.max_jobs_per_month,
    featured_listings = EXCLUDED.featured_listings,
    priority_ranking = EXCLUDED.priority_ranking;
