-- HunarHub Database Schema
-- Version: 1.0.0
-- Generated by Antigravity

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-------------------------------------------------------------------------------
-- 1. Profiles Table (Extends auth.users)
-------------------------------------------------------------------------------
CREATE TYPE user_role AS ENUM ('student', 'recruiter', 'admin');

CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role user_role DEFAULT 'student',
  full_name TEXT,
  avatar_url TEXT,
  headline TEXT,
  bio TEXT,
  skills TEXT[] DEFAULT '{}',
  education JSONB DEFAULT '[]', -- structured as [{school, degree, year}]
  company_details JSONB DEFAULT '{}', -- for recruiters: {name, website, size}
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Secure the profiles table
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone." 
  ON profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." 
  ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." 
  ON profiles FOR UPDATE USING (auth.uid() = id);

-------------------------------------------------------------------------------
-- 2. Projects Table
-------------------------------------------------------------------------------
CREATE TABLE projects (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  cover_image_url TEXT,
  tags TEXT[] DEFAULT '{}',
  demo_link TEXT,
  github_link TEXT,
  likes_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Projects are viewable by everyone." 
  ON projects FOR SELECT USING (true);

CREATE POLICY "Users can insert their own projects." 
  ON projects FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own projects." 
  ON projects FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own projects." 
  ON projects FOR DELETE USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 3. Internships Table
-------------------------------------------------------------------------------
CREATE TYPE internship_type AS ENUM ('Full-time', 'Part-time', 'Remote');
CREATE TYPE internship_status AS ENUM ('Open', 'Closed');

CREATE TABLE internships (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  recruiter_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  title TEXT NOT NULL,
  company_name TEXT NOT NULL,
  location TEXT,
  type internship_type DEFAULT 'Full-time',
  salary_range TEXT,
  requirements TEXT[] DEFAULT '{}',
  status internship_status DEFAULT 'Open',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE internships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Internships are viewable by everyone." 
  ON internships FOR SELECT USING (true);

CREATE POLICY "Recruiters can insert internships." 
  ON internships FOR INSERT 
  WITH CHECK (auth.uid() = recruiter_id); -- Ideally check profile role too via trigger/function

CREATE POLICY "Recruiters can update their own internships." 
  ON internships FOR UPDATE USING (auth.uid() = recruiter_id);

-------------------------------------------------------------------------------
-- 4. Applications Table
-------------------------------------------------------------------------------
CREATE TYPE application_status AS ENUM ('pending', 'interviewing', 'accepted', 'rejected');

CREATE TABLE applications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  internship_id UUID REFERENCES internships(id) ON DELETE CASCADE NOT NULL,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  cover_letter TEXT,
  resume_url TEXT,
  status application_status DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(internship_id, student_id)
);

ALTER TABLE applications ENABLE ROW LEVEL SECURITY;

-- Students can see their own applications
CREATE POLICY "Students can view own applications" 
  ON applications FOR SELECT 
  USING (auth.uid() = student_id);

-- Recruiters can see applications for their internships
CREATE POLICY "Recruiters can view applications for their internships" 
  ON applications FOR SELECT 
  USING (
    EXISTS (
      SELECT 1 FROM internships 
      WHERE internships.id = applications.internship_id 
      AND internships.recruiter_id = auth.uid()
    )
  );

-- Students can create applications
CREATE POLICY "Students can apply" 
  ON applications FOR INSERT 
  WITH CHECK (auth.uid() = student_id);

-- Recruiters can update status
CREATE POLICY "Recruiters can update application status" 
  ON applications FOR UPDATE 
  USING (
    EXISTS (
      SELECT 1 FROM internships 
      WHERE internships.id = applications.internship_id 
      AND internships.recruiter_id = auth.uid()
    )
  );

-------------------------------------------------------------------------------
-- 5. Messages Table
-------------------------------------------------------------------------------
CREATE TABLE messages (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  sender_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  attachment_url TEXT,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own messages" 
  ON messages FOR SELECT 
  USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Users can send messages" 
  ON messages FOR INSERT 
  WITH CHECK (auth.uid() = sender_id);

-------------------------------------------------------------------------------
-- 6. Notifications Table
-------------------------------------------------------------------------------
CREATE TYPE notification_type AS ENUM ('application_update', 'new_message', 'project_like', 'follow');

CREATE TABLE notifications (
  id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  type notification_type NOT NULL,
  reference_id UUID, -- Generic reference to project/app/message ID
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own notifications" 
  ON notifications FOR SELECT 
  USING (auth.uid() = user_id);

-------------------------------------------------------------------------------
-- 7. Triggers for Automatic Profile Creation
-------------------------------------------------------------------------------
-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name',
    COALESCE((new.raw_user_meta_data->>'role')::user_role, 'student')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
